<?php
 
/**
 * TDProject_Project
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 */

$redirectUrl = $this->getRequest()->getAttribute(
    TDProject_Report_Controller_Util_WebRequestKeys::REDIRECT_URL
);

?>
<script type="text/javascript">

	window.location.href="<?php echo $redirectUrl ?>";
	
</script>