<?php
 
/**
 * TDProject_Report
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 */

?>
<script type="text/javascript" charset="utf-8">
<!--

/**
 * Loads the report field with the passed ID and replaces the HTML of the 
 * div containers with the ID #reportField with the form to edit the 
 * requested report field.
 *
 * @param int reportFieldId The ID of the report field to edit
 * @return boolean
 */
function loadReportField(reportFieldId) {

	$.ajax({
	    type: "GET",
	    url: "?path=/reportField&method=edit&reportFieldId=" + reportFieldId,
	    success: function(data) {
	        $('#<?php echo $this->getBlockName() ?>').html(data);
	    }
    });
    
	return false;
}

/**
 * Invokes the method to initialize the HTML for creating a new report field
 * and replaces the HTML of the div container with the ID #reportField with 
 * the HTML code returned.
 *
 * @param int reportId The ID of the report to create the field for
 * @return boolean
 */
function createReportField(reportId) {

	$.ajax({
	    type: "GET",
	    url: "?path=/reportField&method=create&reportIdFk=" + reportId,
	    success: function(data) {
	        $('#<?php echo $this->getBlockName() ?>').html(data);
	    }
    });
    
	return false;
}

/**
 * Invokes the method to initialize the HTML for deleting the report field
 * and replaces the HTML of the div container with the ID #reportField with 
 * the HTML code returned.
 *
 * @param int reportId The ID of the report to delete the field from
 * @param int reportFieldId The ID of the report field to delete
 * @return boolean
 */
function deleteReportField(reportId, reportFieldId) {

	$.ajax({
	    type: "GET",
	    url: "?path=/reportField&method=delete&reportId=" + reportId + "&reportFieldId=" + reportFieldId,
	    success: function(data) {
	    	 window.location.href="<?php echo $this->getRedirectUrl() ?>";
	    }
    });
    
	return false;
}

//-->
</script>
<div id="<?php echo $this->getBlockName() ?>"></div>